// This test was generated by by kyber/sign/ethdss/ethdss_test.go, with
// printTests set to true.
const dssTestNew = ['a3d0a7fc0f65cea648c67907613be759484249007f7868cfb1c8d7df1c3da195',
    '132e12793a42b815a564d3e7b2306736874bf192d188dd7194c5f614450e6a9a',
    '92c38e0673274c8397b8a46c7dacdf81646f5f152ca35d7e810a659e8929459a',
    '9f4f46f60d065e776720bb697593a03ee5e0ed44059d86ff62fe900d939f6a3c',
    'e7af27c7ac343ecdce0010ef7604c475c455a200']

module.exports = dssTestNew