// This test was generated by ethdss_test.go, with printTests set to true
const ethdss_test = [['13950cb9e83dede4fd31683f682a3957e076e37fb4c115ed348ad25ed0a95e15',
   '31cb4f2cf75484d40204246366c3ae02712789b6bd61ba49d7baa94cbaa6fc1f',
   '9d881c21623d1a914c4f62b9f87632c658c5c6d31f6ac4cafa56ffd9236a1193',
   '75722cbe5414ba316b9bb75a5995a66261b8b3f0195e47c4ab09e49042395ca8',
   '35c97284f781defd8670fc2044e61a5b704833d4']]
module.exports = ethdss_test