// This test was generated by ethdss_test.go, with printTests set to true
const ethdss_test = [['6348b9204986bd57228ad4e4925c350eaa35855b9e15493d9815a1a897ab3ee4',
    'fe51b8827a3a2a08dea4ce9fa32c9329182464542e46c127897fafa79474f230',
    'de9419b33de4cbdbc70701ed202ec1d51ab4fbccedc75013ddd9e188de324674',
    'd2f365b352b7f92812a3f0bc9ee6c8dcc3093403a9f266770f4caf2ec9a3859b',
    '6809634a3617c160a2f7193bd72b7f1d56167374']]
module.exports = ethdss_test
